### ISSUE TITLE
WBD Feature returning keyerror: 'layers'

### ISSUE THREAD

**Issue by inskeepjoey** [hyriver/pygeohydro#103]
### What happened?

![image](https://user-images.githubusercontent.com/119536203/228628069-54ab0fa5-7289-46be-84d7-5fb109e221b3.png)
When loading a huc6 byid, received KeyError: "layers"

### What did you expect to happen?

Expected huc6 170900 polygon to be loaded into notebook.

### MVCE confirmation

- [ ] Minimal example — the example is as focused as reasonably possible to demonstrate the underlying issue.
- [ ] Complete example — the example is self-contained, including all data and the text of any traceback.
- [ ] New issue — a search of GitHub Issues suggests this is not a duplicate.

### Environment

<details>

</details>

**Comment by inskeepjoey** [comment]
had loaded pygeohydro module:
from pygeohydro import WBD

**Comment by cheginit** [comment]
I am not able to reproduce the error, please make sure you have the latest versions of HyRiver packages and their dependencies. 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/13016644/228662343-a310a324-684f-4f71-abd5-beb63c4ea44f.png">

Also, please provide info about your environment, following the issue report guidelines using `pygeohydro.show_versions()`. For example, this is mine that works without any issues:

<details>

```console
SYS INFO
--------
commit: None
python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:17:34) [Clang 14.0.6 ]
python-bits: 64
OS: Darwin
OS-release: 22.3.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: None
LOCALE: en_US.UTF-8
libhdf5: 1.12.2
libnetcdf: 4.9.1

PACKAGE                VERSION
-------------------------------
aiodns                 3.0.0
aiohttp                3.8.4
aiohttp-client-cache   0.8.1
aiosqlite              0.18.0
async-retriever        0.14.1.dev11+g08ad47b
bottleneck             1.3.7
brotli                 1.0.9
click                  8.0.3
cytoolz                0.12.0
dask                   2023.3.2
defusedxml             0.7.1
folium                 0.14.0
geopandas              0.12.2
h5netcdf               1.1.0
hydrosignatures        0.14.0
lxml                   4.9.2
matplotlib             3.7.1
netCDF4                1.6.3
networkx               3.0
numba                  0.56.4
numpy                  1.23.5
owslib                 0.28.1
pandas                 1.5.3
py3dep                 0.14.0
pyarrow                11.0.0
pydaymet               0.14.0
pygeohydro             0.14.1.dev20+gfe3d424.d20230324
pygeoogc               0.14.0
pygeos                 N/A
pygeoutils             0.14.0
pynhd                  0.14.0
pynldas2               0.14.0
pyproj                 3.4.1
pytest                 7.2.2
pytest-cov             4.0.0
rasterio               1.3.6
requests               2.28.2
requests-cache         1.0.1
richdem                N/A
rioxarray              0.14.0
scipy                  1.10.1
shapely                2.0.1
tables                 3.7.0
ujson                  5.7.0
urllib3                1.26.15
xarray                 2023.3.0
xdist                  N/A
yaml                   N/A
-------------------------------
```
</details>

**Comment by inskeepjoey** [comment]
Ok, sounds good. I did double check that the dependencies were up to date, I may have missed something. Thanks.

**Comment by inskeepjoey** [comment]
~SYS INFO
--------
commit: 4b9748161d8b0ea1955106322499ea680564179a
python: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:41:22) [MSC v.1929 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: English_United States.1252
libhdf5: 1.12.2
libnetcdf: 4.8.1

PACKAGE                VERSION
-------------------------------
aiodns                 N/A
aiohttp                3.8.4
aiohttp-client-cache   0.8.1
aiosqlite              0.18.0
async-retriever        0.14.0
bottleneck             N/A
brotli                 N/A
click                  8.1.3
cytoolz                0.12.0
dask                   2023.1.0
defusedxml             0.7.1
folium                 0.14.0
geopandas              0.12.2
h5netcdf               1.1.0
hydrosignatures        0.14.0
lxml                   4.9.2
matplotlib             3.7.1
netCDF4                1.6.2
networkx               3.0
numba                  0.56.4
numpy                  1.23.5
owslib                 0.28.1
pandas                 1.5.3
py3dep                 N/A
pyarrow                11.0.0
pydaymet               N/A
pygeohydro             0.14.0
pygeoogc               0.14.0
pygeos                 0.14
pygeoutils             0.14.0
pynhd                  0.14.0
pynldas2               N/A
pyproj                 3.4.1
pytest                 N/A
pytest-cov             N/A
rasterio               1.3.4
requests               2.28.2
requests-cache         1.0.1
richdem                N/A
rioxarray              0.13.3
scipy                  1.10.1
shapely                2.0.1
tables                 N/A
ujson                  5.7.0
urllib3                1.26.15
xarray                 2022.12.0
xdist                  N/A
yaml                   N/A
-------------------------------~

**Comment by cheginit** [comment]
It seems that your `xarray` and `python` versions are outdated. Please create a new environment and only install `pygeohydro` so we can narrow down the issue. Also, please report the full traceback so I can see which line of code is throwing this error.

**Comment by inskeepjoey** [comment]
I have no idea why but I still get the KeyError: 'layers'. I created a new environment and only installed pygeohydro, as well as made sure that the dependencies were the correct versions. I'm not sure what you mean by full traceback. I only get the KeyError: 'layers'  message that I included above in the screen shot. 
![image](https://user-images.githubusercontent.com/119536203/228899418-99fe1265-7cbc-428b-af6c-2dd50db5100e.png)

**Comment by cheginit** [comment]
Can you try running this in an `python` REPL instead of notebook? Maybe notebook is suppressing the full traceback. You can just open up a terminal, activate this environment, then type `python` and write and run your code there. Unless I see which library at what line of code is throwing this error, there's not much I can do, since I cannot reproduce this error on my end. I just created a new env with `mamba create -n test python=3.9 pygeohydro` to be similar to yours and used `python`'s REPL:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/13016644/228902679-1827192c-ed79-4598-b6da-ce7ebb03a5f4.png">

**Comment by inskeepjoey** [comment]
That works when I run in python REPL. I'm curious why notebook is suppressing the full traceback.

![image](https://user-images.githubusercontent.com/119536203/228906075-f793f6d9-b95e-41a6-aca3-087391254a94.png)

**Comment by cheginit** [comment]
I don't know what's wrong with your notebook's instance. I am guessing it has to do with the way that you create python environments that notebook uses.

**Comment by inskeepjoey** [comment]
I'll focus on that for trouble shooting. Thanks for the help.
