### ISSUE TITLE
Inclusion of NLCD 2021 Data

### ISSUE THREAD

**Issue by arschultz** [hyriver/pygeohydro#109]
### Is your feature request related to a problem?

Following the [NLCD 2021 data release announcement](https://www.usgs.gov/centers/eros/news/nlcd-2021-now-available), I'm looking forward to updating workflows to utilize the most recent land cover data. Would it be possible to add the 2021 data for the pygeohydro nlcd functions?

### Describe the solution you'd like

Adding 2021 as a selectable option for the "years" arguments.

**Comment by cheginit** [comment]
Thanks for the suggestion. I am already working on it. I will release a new version with 2021 support soon!
